#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2015-2015: Alignak team, see AUTHORS.txt file for contributors
#
# This file is part of Alignak.
#
# Alignak is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Alignak is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Alignak.  If not, see <http://www.gnu.org/licenses/>.
#
#
# This file incorporates work covered by the following copyright and
# permission notice:
#
#  Copyright (C) 2009-2014:
#     Grégory Starck, g.starck@gmail.com
#     Hartmut Goebel, h.goebel@goebel-consult.de
#     Jean Gabes, naparuba@gmail.com
#     Sebastien Coavoux, s.coavoux@free.fr

#  This file is part of Shinken.
#
#  Shinken is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Shinken is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with Shinken.  If not, see <http://www.gnu.org/licenses/>.

"""
This file is used to test realms usage
"""
import time
from alignak_test import AlignakTest


class TestModules(AlignakTest):
    """
    This class contains the tests for the modules
    """

    def test_module_autogeneration(self):
        """
        Test arbiter auto-generated modules
        :return:
        """
        self.print_header()
        self.setup_with_file('cfg/modules/alignak_modules_autogenerated.cfg')
        self.assertTrue(self.schedulers[0].conf.conf_is_correct)

        # Alignak arbiter creates this auto-generated module if...
        modules = [m.module_alias for m in self.arbiter.myself.modules]
        self.assertListEqual(modules, [
            # command_file
            "NamedPipe-Autogenerated",
        ])
        # ...is in the configuration

        # Alignak arbiter creates auto-generated Broker modules if some parameters
        # are present in the configuration
        modules = [m.module_alias for m in self.brokers[0].modules]
        # Alignak arbiter creates this auto-generated module if...
        self.assertListEqual(modules, [
            # status_file
            "Status-Dat-Autogenerated",
            # log_file
            "Simple-log-Autogenerated",
            # use_syslog
            "Syslog-Autogenerated",
            # service_perfdata_file
            "Service-Perfdata-Autogenerated",
            # host_perfdata_file
            "Host-Perfdata-Autogenerated",
        ])
        # ...is in the configuration

        # Alignak arbiter creates auto-generated Scheduler modules if some parameters
        # are present in the configuration
        modules = [m.module_alias for m in self.schedulers[0].modules]
        # Alignak arbiter creates this auto-generated module if...
        self.assertListEqual(modules, [
            # state_retention_file
            "Nagios-Retention-File-Autogenerated",
        ])
        # ...is in the configuration

