doc-warnings: true
test-warnings: false
strictness: medium
max-line-length: 100
autodetect: true
pep8:
  full: true
pep257:
  run: false
mccabe:
  run: false
requirements:
  - requirements.txt
python-targets:
  - 2
ignore-paths:
  - bin
  - contrib
  - dev
  - doc
  - etc
  - test
ignore-patterns:
# This file is only defining the imported Alignak version
  - alignak/__init__.py
# This file is necessary because imported by daemons but it does not use imported packages...
  - alignak/objects/__init__.py
# This file is for setup only and not yet pep8/pylint compliant
  - install_hooks.py
